[package]
name = "staking"
version = "0.0.0"
authors = ["René Ďuriš"]
edition = "2018"
publish = false

[lib]
path = "src/init.rs"

[dev-dependencies]
num-bigint = "0.4.2"

[dependencies.multiversx-sc]
version = "0.39.5"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.5"
