[package]
name = "staking-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["René Ďuriš"]

[dev-dependencies]

[dependencies.staking]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.5"
