// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           41
// Async Callback (empty):               1
// Total number of exported functions:  43

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    staking
    (
        getAPR
        getTotalStaked
        getStakedPosition
        RPSAcumulated
        getStorageRewards
        getAPRLastTime
        getMinimumStake
        getStakeDeposit
        getProducedRewards
        getProducedRewardsUser
        getStakersList
        getNextNodeStaking
        getUserNode
        getLockStakingState
        getLockTime
        getUnlockFutureTime
        getWithdrawFee
        getBurnOrCirculate
        getEarlyWithdrawingState
        getTokenID
        getStakingModuleState
        getRewards
        getBurnTokens
        getBurnTokensUser
        supplyRewards
        stakingState
        changeAPR
        StakeMinimum
        LockStakeState
        EarlyWithdrawState
        changeLockTime
        changeWithdrawFee
        circulateOrBurn
        stakingSettings
        depositAERO
        withdrawAERO
        claimAERO
        reinvestAERO
        rewardAERO
        AEROStatistics
        userStats
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
